Drymouth-Gulch/Drymouth-Gulch

code/game/machinery/newscaster.dm
code/game/machinery/vending.dm
code/game/objects/flags.dm
code/game/objects/structures/wasteplants.dm
code/modules/food&drinks/food/snacks_other.dm

Foldered all the fixes I made, hopefully in the correct place

Previous fixess, now foldered

---

code/game/jobs/faction/faction.dm

late join fix

---

code/game/jobs/job/legion.dm
code/game/jobs/job/newlegion.dm
code/game/objects/items/stacks/cash.dm

Shouldn't fill their bag with denarii this time around.

Fixes Legion starting with denarii

---

code/controllers/configuration.dm

Makes the restart vote not default non-voters to continue

---

code/modules/projectiles/guns/medbeam.dm

It now heals at 1/4th the rate.

Beam gun nerf

---

code/game/objects/items/weapons/fallout13misc.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/outfits/standard.dm
code/modules/clothing/suits/armor.dm
lootspawners.dm

how did i not know this for 2 days

Fixes BoS being unable to shoot guns

---

code/modules/clothing/head/helmet.dm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm

dont code at 3 in the morning kids

Fixes compile errors

---

code/controllers/configuration.dm
code/controllers/subsystem/voting.dm
code/modules/client/client procs.dm
code/modules/mob/mob.dm
interface/interface.dm

Finally fucking stops counting AFK into the voting system 100% for sure this time
Updates the discord button, makes the non-relevant buttons not work until I figure out how to edit .dmf files properly.

UI+Voting tweaks

---

code/game/objects/items/weapons/storage/belt.dm

Adds stimpaks to the medical belt's whitelist.

Allow Stimpaks in Medical Belts

---

code/modules/food&drinks/kitchen machinery/smartfridge.dm

Adds stimpaks to medical smart fridge whitelist.

Allow Stimpaks in Medical Smart Fridges

---

code/game/objects/items/weapons/storage/belt.dm
code/modules/crafting/recipes.dm

Adds 6 storage slots to the bandolier, and allows it to be craftable with gekkon hide.

Bandolier Buff and Crafting Recipe

---

lewd/_lewd.dm
lewd/lewd_code.dm
lewd/lewd_definitions.dm
lewd/lewd_mob.dm

- Adds "mount with ass" for males and females users
- Adds "finger their ass" for males and female targets
- Adds handjobs
- Adds breastfucking
- I'm a degenerate

Adds More Lewd Options

---

lewd/_lewd.dm
lewd/lewd_definitions.dm
lewd/lewd_mob.dm

Fix for male breastfucking

---

code/modules/projectiles/projectile/bullets.dm

Any shotgun shell that uses pellets now has a max range of 7 tiles.
Buckshot damage reduced to 15, armor penetration decreased to -20
ren has been bugging me for weeks pls merge before he cuts me

Shotgun nerf

---

code/controllers/configuration.dm

some people wanted this, including ren, let's see how this goes

Sets run speed to 5

---

code/modules/research/designs/weapon_designs.dm

Fixes the ammo being in the weapons category also removes the op stuff

---

code/modules/vehicles/vehicle.dm

i dont have to be on a motorcycle to get you catto i swear to god

Makes vehicles unable to drive indoors

---

lootspawners.dm

Removes stimulants from the loot spawner

---

code/modules/paperwork/paper.dm

Fixes field crash exploit, makes paper great again

---

code/modules/clothing/suits/armor.dm
code/modules/clothing/under/miscellaneous.dm
lootspawners.dm

buffs power armor, buffs recon armor, nerfs vet ranger armor
makes T-45b salvaged not require power armor training
removes enclave uniform from the tier5 spawnlist

armor balancing v.whatever

---

code/game/machinery/autolathe.dm

>when you realize it's probably never going to get fixed

Fixes 5x 10x autolathe, converts coeff to use '*' instead of '/' due to bugs

---

code/game/machinery/autolathe.dm
code/modules/clothing/suits/armor.dm

@Reverts Drymouth-Gulch/Drymouth-Gulch#115

Revert "fixin shit"

---

code/game/machinery/autolathe.dm
code/modules/clothing/suits/armor.dm

Reverts Drymouth-Gulch/Drymouth-Gulch#118

Revert "Revert "fixin shit""

---

code/modules/clothing/outfits/standard.dm

adds access level 73 to bos ids, removes their full vault access that they had for some reason

Fixes BOS ids, again

---

code/game/objects/items/weapons/weaponry.dm

whoops dont drink and code kids

Unfucks katanas and claymores

---

code/game/objects/items/weapons/shields.dm
code/game/objects/items/weapons/storage/backpack.dm
code/game/objects/weapons.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/vehicles/motorcycle.dm
config/tips.txt

- Quivers and Shields [P1 + P2] 
- Syntax and Grammar Errors x2
- Motorcycle cells
- Tips

Bug Fixes - 10/11/17

---

code/game/communications.dm
code/game/machinery/telecomms/broadcasting.dm
code/game/objects/items/devices/radio/encryptionkey.dm
code/game/objects/items/devices/radio/headset.dm
code/modules/clothing/outfits/standard.dm

- Creates brotherhood channel
- Creates brotherhood headsets
- Gives Scribes, Initiates, Knights, and Paladins brotherhood headsets

Gives Brotherhood their own channel and headsets [10/12/17]

---

code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/projectile.dm
code/modules/projectiles/guns/projectile/automatic.dm
code/modules/projectiles/guns/projectile/launchers.dm
code/modules/projectiles/guns/projectile/pistol.dm
code/modules/projectiles/guns/projectile/revolver.dm
code/modules/projectiles/guns/projectile/saw.dm
code/modules/projectiles/guns/projectile/shotgun.dm

read commits makes everything better

blah blah blah guns and shit

---

code/modules/reagents/chemistry/recipes/pyrotechnics.dm

Mostly because of the vault, REALLY cheap explosions that have no massive drawbacks (black powder needs to wait a bit before exploding, bit harder to make, nitro is also harder to make) and can also detonate instantly.

Water + potassium explosions are now REALLY weak

---

code/modules/clothing/head/ncr.dm

https://gyazo.com/5ee90bc24cad9a0a5d483b9a6280e6ba

cause ren said so
